apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: smart-grocer-nodejs
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-grocer-nodejs
      tier: frontend
  template:
    metadata:
      labels:
        app: smart-grocer-nodejs
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http-server
          containerPort: 8060
        env:
        - name: PORT
          value: "8060"
        - name: LOGIN_API
          value: login-service:8081
        - name: RECIPE_API
          value: recipes-service:8082
        - name: PANTRY_API
          value: pantry-service:8084
