apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    app: smart-grocer-nodejs
    tier: backend
    svc: login
spec:
  type: ClusterIP
  selector:
    app: smart-grocer-nodejs
    tier: backend
    svc: login
  ports:
  - port: 8081
    targetPort: http-server
