apiVersion: apps/v1
kind: Deployment
metadata:
  name: pantry-service
  labels:
    app: smart-grocer-nodejs
    svc: pantry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-grocer-nodejs
      svc: pantry
  template:
    metadata:
      labels:
        app: smart-grocer-nodejs
        svc: pantry
    spec:
     containers:
      - name: pantry-backend
        image: pantry-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http-server
          containerPort: 8064
        env:
        - name: PORT
          value: "8064"