apiVersion: v1
kind: Service
metadata:
  name: pantry-service
  labels:
    app: smart-grocer-nodejs
    svc: pantry
spec:
  type: ClusterIP
  selector:
    app: smart-grocer-nodejs
    svc: pantry
  ports:
  - port: 8084
    targetPort: http-server
