apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-service
  labels:
    app: smart-grocer-nodejs
    svc: recipes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-grocer-nodejs
      svc: recipes
  template:
    metadata:
      labels:
        app: smart-grocer-nodejs
        svc: recipes
    spec:
     containers:
      - name: recipes-backend
        image: recipes-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "750Mi"
            cpu: "750m"
        ports:
        - name: http-server
          containerPort: 8065
        env:
        - name: PORT
          value: "8065"